# Generated by Django 6.0.5 on 2026-05-20 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadeUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_habilidade', to='habilidades.habilidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_usuario', to='perfis.perfil')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'habilidade'), name='unique_usuario_habilidade')],
            },
        ),
    ]
