# Generated by Django 6.0.5 on 2026-05-20 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('freelancer', 'Freelancer')], max_length=20)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='servicos.servico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='perfis.perfil')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('servico', 'usuario', 'tipo'), name='unique_servico_usuario_tipo')],
            },
        ),
    ]
