# Generated by Django 6.0.5 on 2026-05-20 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('aceita', 'Aceita'), ('pendente', 'Pendente'), ('rejeitada', 'Rejeitada')], max_length=50)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='perfis.perfil')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='servicos.servico')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vaga', 'freelancer'), name='unique_vaga_freelancer')],
            },
        ),
    ]
